apiVersion: nifi.orange.com/v1alpha1
kind: NifiRegistryClient
metadata:
  name: registry-client-example
  namespace: nifi
spec:
  clusterRef:
    name: simplenifi
    namespace: nifi
  description: "Registry client managed by NiFiKop"
  uri: "https://nifi-registry-0:19443"