apiVersion:  nifi.orange.com/v1alpha1
kind: NifiUser
metadata:
  name: nifi-registry-0
  namespace: nifi
spec:
  clusterRef:
    name: sslnifi
  secretName: registry-client-secret1
  createCert: true
  includeJKS: true