apiVersion:  nifi.orange.com/v1alpha1
kind: NifiUser
metadata:
  name: 34.140.15.40
  namespace: nifi
spec:
  clusterRef:
    name: sslnifi
  secretName: registry-ssl
  createCert: true
  includeJKS: true