apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi-registry
spec:
  serviceName: nifi-registry
  replicas: 1
  selector:
    matchLabels:
      app: nifi-registry
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - nifi-registry
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nifi-registry
          image: apache/nifi-registry:latest
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    cat /opt/nifi-registry/nifi-registry-current/nifi-registry.properties/nifi-registry.properties > /opt/nifi-registry/nifi-registry-current/conf/nifi-registry.properties
                    cat /opt/nifi-registry/nifi-registry-current/nifi-registry.properties/authorizers.xml > /opt/nifi-registry/nifi-registry-current/conf/authorizers.xml
          ports:
            - containerPort: 19443
          volumeMounts:
            - name: registryssl
              mountPath: /opt/nifi-registry/nifi-registry-current/keystore.jks
              subPath: keystore.jks
            - name: registryssl
              mountPath: /opt/nifi-registry/nifi-registry-current/truststore.jks
              subPath: truststore.jks
            - name: registryproperties
              mountPath: /opt/nifi-registry/nifi-registry-current/nifi-registry.properties
          env:
            - name: FLOW_PROVIDER
              value: "git"
            - name: GIT_REMOTE_URL
              value: "http://10.70.10.16/SarahAlzahrani/nififlowdesign.git"
            - name: GIT_CHECKOUT_BRANCH
              value: "master"
            - name: FLOW_PROVIDER_GIT_FLOW_STORAGE_DIRECTORY
              value: "/opt/nifi-registry/flow-storage-git"
            - name: FLOW_PROVIDER_GIT_REMOTE_TO_PUSH
              value: "origin"
            - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_USER
              value: "sarahalzahrani"
            - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_PASSWORD
              value: "Sarah1234"
            - name: GIT_CONFIG_USER_NAME
              value: "APACHE NIFI REGISTRY"
            - name: GIT_CONFIG_USER_EMAIL
              value: ""
      volumes:
        - name: registryssl
          projected:
            sources:
            - secret:
                name: registry-ssl
                items:
                  - key: keystore.jks
                    path: keystore.jks
                  - key: truststore.jks
                    path: truststore.jks
        - name: registryproperties
          configMap:
            name: registry-properties
  # volumeClaimTemplates:
  # - metadata:
  #     name: flowfilerepository
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 5Gi
  #     storageClassName: gp2s