apiVersion: nifi.orange.com/v1alpha1
kind: NifiDataflow
metadata:
  name: dataflow-lifecycle
spec:
  # parentProcessGroupID: "3b055d9c-017b-1000-d484-f94be84c4cf3"
  bucketId: "61b136da-fefb-4619-b50d-365271180962"
  flowId: "df5ecc7c-f75d-4b29-9b16-62e956094fbf"
  flowVersion: 1
  runOnce: false
  skipInvalidControllerService: true
  skipInvalidComponent: true
  clusterRef:
    name: testnifi
    namespace: nifi
  registryClientRef:
    name: registry-client-nifikop
    namespace: nifi
  parameterContextRef:
    name: dataflow-lifecycle
    namespace: nifi
  updateStrategy: drop