apiVersion: v1
kind: Service
metadata:
  name: registry-static-lb
  labels:
    app: nifi-registry
spec:
  selector:
    app: nifi-registry
  ports:
  - port: 18080
    targetPort: 18080
  type: LoadBalancer
  loadBalancerIP: 34.78.170.244