apiVersion: v1
kind: Service
metadata:
  name: nifi-static-lb
  labels:
    app: nifi
    nifi_cr: sslnifi
spec:
  selector:
    app: nifi
    nifi_cr: sslnifi
  ports:
  - port: 8443
    targetPort: 8443
  type: LoadBalancer
  loadBalancerIP: 35.205.55.108