apiVersion: v1
kind: Service
metadata:
  name: nifi-static-lb
  labels:
    app: nifi
    nifi_cr: testnifi
spec:
  selector:
    app: nifi
    nifi_cr: testnifi
  ports:
  - port: 8443
    targetPort: 8443
  type: LoadBalancer
  loadBalancerIP: 34.79.208.247