apiVersion: v1
kind: Service
metadata:
  name: registry-static-lb
  labels:
    app: nifi-registry
spec:
  selector:
    app: nifi-registry
  ports:
  - port: 19443
    targetPort: 19443
  type: LoadBalancer
  loadBalancerIP: 34.140.15.40