apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain