kind: Service
apiVersion: v1
metadata:
  name: nifi-registry-http
spec:
  type: LoadBalancer
  selector:
    app: nifi-registry
  ports:
    - protocol: TCP
      port: 19443
      targetPort: 19443
      name: nifi

---

kind: Service
apiVersion: v1
metadata:
  name: nifi-registry
spec:
  clusterIP: None
  selector:
    app: nifi-registry
  ports:
    - protocol: TCP
      port: 19443
      targetPort: 19443
      name: nifi-registry-listen-http