apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-logs-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: nifi-logs-disk1
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain