apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-logs-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-cluster-1-default-pool-e937016a-7jb5
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain