apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-provenance-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: nifi-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain