apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_DATABASE: keycloak
    POSTGRES_EXTERNAL_ADDRESS: "34.140.58.4"
    POSTGRES_EXTERNAL_PORT: "5432"
    POSTGRES_HOST: "keycloak-postgresql"
    POSTGRES_PASSWORD: "123456"
    POSTGRES_SUPERUSER: "true"
    POSTGRES_USERNAME: keycloak-user