apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-cluster
  labels:
    app: keycloak-cluster
spec:
  instances: 1
  externalAccess:
    enabled: True
  externalDatabase:
    enabled: True