apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_DATABASE: keycloakDB
    POSTGRES_EXTERNAL_ADDRESS: "34.78.170.244"
    POSTGRES_EXTERNAL_PORT: "5432"
    POSTGRES_HOST: "keycloak-postgresql"
    POSTGRES_PASSWORD: "XcDw"
    POSTGRES_SUPERUSER: true
    POSTGRES_USERNAME: keycloak