apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: test
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:15.0.1
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: mysql
        - name: DB_ADDR
          value: "mysql.mysql.svc.cluster.local"
        - name: DB_DATABASE
          value: keycloak
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: keycloak-user
        - name: DB_PASSWORD
          value: "123456"
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        # - name: JGROUPS_DISCOVERY_PROPERTIES
        #   value: 'dns_query=external-mysql-db.iam'
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 30