apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 2
  # externalAccess:
  #   enabled: True
  externalDatabase:
    enabled: True