apiVersion: v1
kind: Service
metadata:
  name: keycloak-static-lb
  labels:
    app: keycloak-0
spec:
  selector:
    app: keycloak-0
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 34.79.78.207