apiVersion: v1
kind: Service
metadata:
  name: keycloak-static-lb
  labels:
    app: keycloak
    component: keycloak
spec:
  selector:
    app: keycloak
    component: keycloak
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 34.79.78.207