apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
type: Opaque
stringData:
    MYSQL_DATABASE: keycloak
    MYSQL_EXTERNAL_ADDRESS: "34.140.250.41"
    MYSQL_EXTERNAL_PORT: "3306"
    MYSQL_HOST: "mysql"
    MYSQL_PASSWORD: "123456"
    MYSQL_SUPERUSER: "true"
    MYSQL_USERNAME: keycloak-user