apiVersion: v1
kind: Service
metadata:
  name: keycloak-hs
  namespace: test
  labels:
    app: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak