kind: Service
apiVersion: v1
metadata:
  name: nifi-registry-static-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.79.205.129
  selector:
    app: nifi-registry
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
      name: nifi

---

kind: Service
apiVersion: v1
metadata:
  name: nifi-registry
spec:
  selector:
    app: nifi-registry
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
      name: nifi-registry-cluster-ip