apiVersion:  nifi.orange.com/v1alpha1
kind: NifiUser
metadata:
  name: nifi-registry-0.nifi-registry.nifi.svc.cluster.local
  namespace: nifi
spec:
  clusterRef:
    name: sslnifi
  secretName: registry-ssl
  createCert: true
  includeJKS: true